// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `UserMap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __UserMap_h__
#define __UserMap_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace DR
{

class UserMap;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::DR::UserMap>&);
::IceProxy::Ice::Object* upCast(::IceProxy::DR::UserMap*);

}

}

namespace DR
{

class UserMap;
bool operator==(const UserMap&, const UserMap&);
bool operator<(const UserMap&, const UserMap&);
::Ice::Object* upCast(::DR::UserMap*);
typedef ::IceInternal::Handle< ::DR::UserMap> UserMapPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::DR::UserMap> UserMapPrx;
void __patch(UserMapPtr&, const ::Ice::ObjectPtr&);

}

namespace DR
{

class Callback_UserMap_addUserToLocation_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserMap_addUserToLocation_Base> Callback_UserMap_addUserToLocationPtr;

class Callback_UserMap_getUsersNearLocation_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserMap_getUsersNearLocation_Base> Callback_UserMap_getUsersNearLocationPtr;

class Callback_UserMap_removeFromMap_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserMap_removeFromMap_Base> Callback_UserMap_removeFromMapPtr;

}

namespace IceProxy
{

namespace DR
{

class UserMap : virtual public ::IceProxy::Ice::Object
{
public:

    void addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y)
    {
        addUserToLocation(userID, x, y, 0);
    }
    void addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx)
    {
        addUserToLocation(userID, x, y, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addUserToLocation(userID, x, y, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addUserToLocation(userID, x, y, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addUserToLocation(userID, x, y, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addUserToLocation(userID, x, y, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y)
    {
        return begin_addUserToLocation(userID, x, y, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx)
    {
        return begin_addUserToLocation(userID, x, y, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUserToLocation(userID, x, y, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUserToLocation(userID, x, y, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::DR::Callback_UserMap_addUserToLocationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUserToLocation(userID, x, y, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx, const ::DR::Callback_UserMap_addUserToLocationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUserToLocation(userID, x, y, &__ctx, __del, __cookie);
    }

    void end_addUserToLocation(const ::Ice::AsyncResultPtr&);
    
private:

    void addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance)
    {
        return getUsersNearLocation(x, y, distance, 0);
    }
    ::std::string getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& __ctx)
    {
        return getUsersNearLocation(x, y, distance, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getUsersNearLocation(x, y, distance, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getUsersNearLocation(x, y, distance, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getUsersNearLocation(x, y, distance, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getUsersNearLocation(x, y, distance, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::DR::UserMapPrx __proxy = ::DR::UserMapPrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_getUsersNearLocation(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_getUsersNearLocation(x, y, distance, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance)
    {
        return begin_getUsersNearLocation(x, y, distance, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& __ctx)
    {
        return begin_getUsersNearLocation(x, y, distance, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUsersNearLocation(x, y, distance, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUsersNearLocation(x, y, distance, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::DR::Callback_UserMap_getUsersNearLocationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUsersNearLocation(x, y, distance, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int x, ::Ice::Int y, ::Ice::Int distance, const ::Ice::Context& __ctx, const ::DR::Callback_UserMap_getUsersNearLocationPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUsersNearLocation(x, y, distance, &__ctx, __del, __cookie);
    }

    ::std::string end_getUsersNearLocation(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y)
    {
        removeFromMap(userID, x, y, 0);
    }
    void removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx)
    {
        removeFromMap(userID, x, y, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_removeFromMap(userID, x, y, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_removeFromMap(userID, x, y, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_removeFromMap(userID, x, y, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_removeFromMap(userID, x, y, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y)
    {
        return begin_removeFromMap(userID, x, y, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx)
    {
        return begin_removeFromMap(userID, x, y, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFromMap(userID, x, y, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFromMap(userID, x, y, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::DR::Callback_UserMap_removeFromMapPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFromMap(userID, x, y, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int userID, ::Ice::Int x, ::Ice::Int y, const ::Ice::Context& __ctx, const ::DR::Callback_UserMap_removeFromMapPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_removeFromMap(userID, x, y, &__ctx, __del, __cookie);
    }

    void end_removeFromMap(const ::Ice::AsyncResultPtr&);
    
private:

    void removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<UserMap> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_secure(bool __secure) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_twoway() const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_oneway() const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_batchOneway() const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_datagram() const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_batchDatagram() const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_compress(bool __compress) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_timeout(int __timeout) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<UserMap> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<UserMap*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace DR
{

class UserMap : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::std::string getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace DR
{

class UserMap : virtual public ::IceDelegate::DR::UserMap,
                virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace DR
{

class UserMap : virtual public ::IceDelegate::DR::UserMap,
                virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace DR
{

class UserMap : virtual public ::Ice::Object
{
public:

    typedef UserMapPrx ProxyType;
    typedef UserMapPtr PointerType;

    UserMap()
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void addUserToLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addUserToLocation(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string getUsersNearLocation(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getUsersNearLocation(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void removeFromMap(::Ice::Int, ::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___removeFromMap(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const UserMap& l, const UserMap& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const UserMap& l, const UserMap& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace DR
{

template<class T>
class CallbackNC_UserMap_addUserToLocation : public Callback_UserMap_addUserToLocation_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_UserMap_addUserToLocation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_addUserToLocation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_addUserToLocation<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_addUserToLocation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_addUserToLocation<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserMap_addUserToLocation : public Callback_UserMap_addUserToLocation_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_UserMap_addUserToLocation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_addUserToLocation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_addUserToLocation<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_addUserToLocation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_addUserToLocationPtr
newCallback_UserMap_addUserToLocation(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_addUserToLocation<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_UserMap_getUsersNearLocation : public Callback_UserMap_getUsersNearLocation_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_UserMap_getUsersNearLocation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::DR::UserMapPrx __proxy = ::DR::UserMapPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getUsersNearLocation(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserMap_getUsersNearLocationPtr
newCallback_UserMap_getUsersNearLocation(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_getUsersNearLocation<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserMap_getUsersNearLocationPtr
newCallback_UserMap_getUsersNearLocation(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_getUsersNearLocation<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserMap_getUsersNearLocation : public Callback_UserMap_getUsersNearLocation_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_UserMap_getUsersNearLocation(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::DR::UserMapPrx __proxy = ::DR::UserMapPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getUsersNearLocation(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserMap_getUsersNearLocationPtr
newCallback_UserMap_getUsersNearLocation(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_getUsersNearLocation<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_getUsersNearLocationPtr
newCallback_UserMap_getUsersNearLocation(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_getUsersNearLocation<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_UserMap_removeFromMap : public Callback_UserMap_removeFromMap_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_UserMap_removeFromMap(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_removeFromMap<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_removeFromMap<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_removeFromMap<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserMap_removeFromMap<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserMap_removeFromMap : public Callback_UserMap_removeFromMap_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_UserMap_removeFromMap(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_removeFromMap<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_removeFromMap<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_removeFromMap<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserMap_removeFromMapPtr
newCallback_UserMap_removeFromMap(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserMap_removeFromMap<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
